-- MySQL Script generated by MySQL Workbench
-- 11/01/17 04:33:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`planeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planeta` (
  `idplaneta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sistema` VARCHAR(45) NOT NULL,
  `TC` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idplaneta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alien` (
  `idalien` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `planeta_idplaneta` VARCHAR(45) NOT NULL,
  `TC` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idalien`),
  INDEX `fk_alien_planeta1_idx` (`planeta_idplaneta` ASC),
  CONSTRAINT `fk_alien_planeta1`
    FOREIGN KEY (`planeta_idplaneta`)
    REFERENCES `mydb`.`planeta` (`idplaneta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nave` (
  `idnave` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `formato` VARCHAR(45) NOT NULL,
  `alien_idalien` VARCHAR(45) NOT NULL,
  `TC` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idnave`),
  INDEX `fk_nave_alien_idx` (`alien_idalien` ASC),
  CONSTRAINT `fk_nave_alien`
    FOREIGN KEY (`alien_idalien`)
    REFERENCES `mydb`.`alien` (`idalien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `patente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
